import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from pathlib import Path
import os

# CONFIG
DATA_FILE = "data/training/contract_fraud_dataset.csv"
OUTPUT_DIR = "generated_contracts"
SAMPLES_PER_LABEL = 5

def create_pdf(text, label, index, output_path):
    c = canvas.Canvas(str(output_path), pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, height - 100, f"LEGAL AGREEMENT - {label.upper()}")
    
    # Label metadata (small)
    c.setFont("Helvetica", 10)
    c.drawString(100, height - 120, f"Classification: {label}")
    c.drawString(100, height - 135, f"Document ID: {label}_{index}")
    
    # Content
    c.setFont("Helvetica", 12)
    text_object = c.beginText(100, height - 180)
    text_object.setFont("Helvetica", 12)
    
    # Wrap text manually if needed, but for now we trust standard sizing
    # Simple line breaker for demonstration
    lines = text.split('\n')
    for line in lines:
        # Avoid overflow (rudimentary)
        while len(line) > 80:
            text_object.textLine(line[:80])
            line = line[80:]
        text_object.textLine(line)
        
    c.drawText(text_object)
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(100, 50, "Generated by Legal Assistant AI - Research Purposes Only")
    
    c.save()
    print(f"Generated: {output_path.name}")

def main():
    base_dir = Path(__file__).resolve().parent.parent
    data_path = base_dir / DATA_FILE
    output_base = base_dir / OUTPUT_DIR
    
    if not data_path.exists():
        print(f"Error: {data_path} not found.")
        return
        
    print(f"Loading data from {data_path}...")
    df = pd.read_csv(data_path)
    
    for label in ["Safe", "Risky", "Fraudulent"]:
        label_dir = output_base / label
        label_dir.mkdir(parents=True, exist_ok=True)
        
        subset = df[df['label'] == label].head(SAMPLES_PER_LABEL)
        print(f"Generating {len(subset)} {label} contract PDFs...")
        
        for i, (idx, row) in enumerate(subset.iterrows()):
            filename = f"{label.lower()}_contract_{i+1}.pdf"
            create_pdf(row['text'], label, i+1, label_dir / filename)

if __name__ == "__main__":
    main()
