def create_fir_pdf(data: dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
        import io

        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=A4)
        c.drawString(72, 800, data.get('title', 'FIR'))
        c.drawString(72, 780, data.get('body', 'No content'))
        c.showPage()
        c.save()
        buf.seek(0)
        return buf.read()
    except Exception:
        return (data.get('title', '') + '\n' + data.get('body', '')).encode('utf-8')


from app.services.ollama_service import OllamaService

class ReportGeneratorService:
    def generate_fir(self, text: str, sections: list) -> str:
        """Generate a structured FIR report text (LLM-enhanced)."""
        
        # 1. Prepare context from sections
        formatted_sections = ""
        if not sections:
            formatted_sections = "No specific IPC/CrPC sections identified automatically."
        else:
            for s in sections:
                sid = s.get('section_id', 'Unknown')
                title = s.get('title', '')
                text = s.get('text', '') # Full legal text
                # Include full info in context for LLM
                formatted_sections += f"- SECTION: {sid}\n  TITLE: {title}\n  CONTENT: {text}\n\n"

        # 2. Try LLM Generation
        if OllamaService.is_available():
            prompt = f"""You are an expert police officer and India Legal Assistant. Draft a professional First Information Report (FIR) based ONLY on the provided incident and legal sections.
            
            INCIDENT:
            "{text}"
            
            LEGAL SECTIONS FOUND (Use these strictly):
            {formatted_sections}
            
            INSTRUCTIONS:
            1. **STRICT RELEVANCE**: Only use sections that are DIRECTLY applicable to the crime. 
               - FAIL validation for "Explanation" or "Definition" sections unless the main offense section is also present.
               - If a section score seems low or irrelevant to the text, IGNORE it.
            2. **Output Format**:
               - First Information Report (FIR)
               - [Body of FIR]
               - **Offenses Registered**: List strictly the applied sections (e.g., "IPC 379: Punishment for Theft"). *Do not list irrelevant ones.*
            3. **Speed & Conciseness**: Be professional but concise.
            4. Do not hallucinate.
            """
            
            llm_response = OllamaService.generate_text(prompt)
            if llm_response:
                return llm_response + "\n\n*(Generated by Local AI via Ollama)*"

        # 3. Fallback to Template
        return f"""**FIRST INFORMATION REPORT (DRAFT)**

**1. Incident Summary:**
{text}

**2. Applicable Legal Sections Identified:**
{formatted_sections}

**3. Next Steps:**
- Verify these sections with a legal practitioner.
- File this FIR at the nearest police station under jurisdiction.
- Provide any evidence (photos, documents) mentioned in the incident.

*Generated by AI Legal Assistant (Template Mode)*"""
